### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Guy0nTheInternet3333** [DMDCR/Minecraft-RenderDragonRemoval#1]

**Comment by DMDCR** [comment]
It replaces your minecraft bedrock with the last version with the old rendering engine, just run it and reinstall your bedrock from it :D

**Comment by Guy0nTheInternet3333** [comment]
Can this be used in Android?

**Comment by DMDCR** [comment]
> Can this be used in Android?

No. Only on windows :(
